---
before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes yamllint shellcheck
build:
  script:
    - yamllint .gitlab-ci.yml
    - shellcheck -x \
      scripts/build.sh \
      scripts/get_source.sh \
      scripts/prebuild.sh \
      scripts/setup-android-sdk.sh
