name: build-mull
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions/setup-java@v4
        name: Setup JDK
        with:
          distribution: 'temurin'
          java-version: |
            8
            17
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y make \
                    cmake \
                    clang \
                    gyp \
                    ninja-build \
                    patch \
                    perl \
                    wget \
                    unzip \
                    zlib1g-dev
      - name: Setup Gradle
        run: |
          mkdir -p $HOME/bin
          wget https://gitlab.com/fdroid/fdroidserver/-/raw/master/gradlew-fdroid -O "$HOME/bin/gradle"
          chmod +x "$HOME/bin/gradle"

          mkdir -p ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.configuration-cache=false" >> ~/.gradle/gradle.properties
      - name: Setup Environment
        run: |
          export PATH=$PATH:$HOME/bin
          export JAVA_HOME=$JAVA_HOME_17_X64
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Build
        run: |
          unset ANDROID_HOME
          unset ANDROID_NDK

          python3.9 -m venv env
          source env/bin/activate

          python -m pip install tqdm requests
          python ./scripts/get_sources.py

          source scripts/setup-android-sdk.sh
          source scripts/paths_local.sh

          ./scripts/prebuild.sh
          ./scripts/build.sh
      
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: IronFox APKs
          path: gecko/mobile/android/fenix/app/build/outputs/apk/fenix/release/app-*-release-unsigned.apk