name: Build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build by ${{ github.actor }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Remove unused packages
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: true

    - name: Run script
      run: |
        bash ./scripts/github-build.sh

    - name: Upload apk
      uses: actions/upload-artifact@v4
      with:
        name: archive_apk
        path: gecko/mobile/android/fenix/app/build/outputs/apk/fenix/release/*.apk

    - name: Upload aab
      uses: actions/upload-artifact@v4
      with:
        name: archive_aab
        path: gecko/mobile/android/fenix/app/build/outputs/bundle/fenixRelease/*.aab
